# Generated by Django 2.2.16 on 2021-11-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211125_2031'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='uniqe_following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_following'),
        ),
    ]
